version: '3.4'

#Сеть
networks:
  #Название сети
  mynetwork:
    #Доступ к сети
    external:
      name: gateway_mynetwork
  rabbit_net:
    external:
      name: gateway_rabbit_net

services:
  #Название сервиса
  books:
    #Название контейнера
    container_name: books
    #Сборка контейнера
    build:
      #Путь к Dockerfile для сборки
      context: ./
    environment:
      NODE_ENV: production
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - "3001:3001"
    # Названия сетей, в которых работает контейнер
    networks:
      - mynetwork
      - rabbit_net