version: '3.4'

#Сеть
networks:
  #Название сети
  mynetwork:
    #Доступ к сети
    external:
      name: gateway_mynetwork
  rabbit_net:
    external:
      name: gateway_rabbit_net

services:
  #Название сервиса
  auth:
    #Название контейнера
    container_name: auth
    #Сборка контейнера
    build:
      #Путь к Dockerfile для сборки
      context: ./
    environment:
      NODE_ENV: production
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - "3000:3000"
    #Название сетей в которых работает контейнер
    networks:
      - mynetwork
      - rabbit_net